title: Jaren N Ashcraft
url: "https://jashcraf.github.io"
baseurl: "/"

description: My website that covers my professional and personal endeavors

author:
  name: Jaren N Ashcraft
  email: jashcraft@email.arizona.edu
